basePath: /
definitions:
  domain.Children:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.ChildrenObj'
        type: array
    type: object
  domain.ChildrenObj:
    properties:
      id:
        type: string
    type: object
  domain.Instagram:
    properties:
      caption:
        type: string
      children:
        $ref: '#/definitions/domain.Children'
      id:
        type: string
      media_type:
        type: string
      media_url:
        type: string
      permalink:
        type: string
      thumbnail_url:
        type: string
      timestamp:
        type: string
      username:
        type: string
    type: object
  domain.InstagramData:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Instagram'
        type: array
    type: object
  dto.InstaResponse:
    properties:
      data:
        $ref: '#/definitions/domain.InstagramData'
    type: object
host: 127.0.0.1:4000
info:
  contact: {}
  title: gostagram Swagger API
  version: "1.0"
paths:
  /api/v1/instagram/posts:
    get:
      description: Instagram get posts by user
      parameters:
      - description: user id
        in: query
        name: user_id
        required: true
        type: string
      - description: access token
        in: query
        name: access_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.InstaResponse'
      summary: Instagram get posts by user
swagger: "2.0"
